### ISSUE TITLE
安卓端qq登录报错(110404)

### ISSUE THREAD

**Issue by shlijie** [iVanPan/react-native-qqsdk#10]
qqsdk实装上以后，ios端登录没问题，然后安卓报错了，登录授权失败（错误码:110404）
react-native-qqsdk/android/build.gradle里的QQ_APP_ID我设置过了，不知道为什么报这个错

**Comment by iVanPan** [comment]
@shlijie  android构建的时候 会合成新的Androidmanifest，看那里QQ_APP_ID 正不正确

**Comment by shlijie** [comment]
问题找到了，QQ_APP_ID只要【1101112313】这样的数字，不能加【tencent】的，就是这个问题。
我看了下源码，里面已经加过了tencent
