### ISSUE TITLE
appid能否传进去而不是在package.json里配置？否则不方便和其他appid一起管理了

### ISSUE THREAD

**Issue by 277850318** [iVanPan/react-native-qqsdk#13]

**Comment by iVanPan** [comment]
@277850318  你说的和其他 appid 一起管理是指所有各种不同的 appid 都放在一个 js 文件里面 或是 JSON文件里面变成一个常量一样去读取吗？

- 首先 QQ 的 SDK 除了在本地代码初始化的时候需要 appid 以外还需要在 AndroidManifest 和 Xcode 的URLTypes 里面添加，而插件在初始化的时候是可以通过代码从这两个地方读取到 appid 的。

- 其次 appid 放在 package.json 里面主要有两个目的：一个是方便 gradle 读取将 appid 写入 AndroidManifest，第二个是方便团队协作

- 我希望使用者只要关心核心 API 的调用就行了，至于配置的东西可以尽量的少花时间，所以这个类库的安装我也推荐使用 react-native link 的方式

**Comment by 277850318** [comment]
ok,看来确实是做不到所有的地方都从配置文件里读取了，
我本来是想弄个config.js,然后里面会有
{
debug:{
   qq_appid,
   wx_appid,
  weibo_appid
},
product:{
   qq_appid,
   wx_appid,
  weibo_appid
}
}
