### ISSUE TITLE
Totally Virus and Spam and Shit and Rubbish

### ISSUE THREAD

**Issue by chimumao** [iVanPan/react-native-qqsdk#17]
Lots of spam files install while "uninstall" this module.
Go to hell and stop hurting coders.

**Comment by erichua23** [comment]
@chimumao You can publish the error information to help the author fix if it's a bug, or create a PR.
Only nonsense dirty words.
I think you should "Go to hell and stop hurting open source contributor."

**Comment by iVanPan** [comment]
@chimumao  can you tell me some detail about 'spam files'
