### ISSUE TITLE
关于点击QQ分享的内容下面会带着app的图标和名字，返回APP使得APP重启

### ISSUE THREAD

**Issue by lwanqiang** [iVanPan/react-native-qqsdk#19]
QQ分享中 分享的内容下面会带着app的图标和名字 点击这个图标和名字的区域 会返回我们的应用，但是这样会使我们的程序重新启动，而不是回到原本的界面

**Comment by erichua23** [comment]
看一下你的主Activity的launchMode是啥，singleTop可能会重新拉起了一个主Activity，你可以检查一下你Activity栈确认一下是不是因为这.
