### ISSUE TITLE
React/RCTLinkingManager.h file not found 

### ISSUE THREAD

**Issue by HengCC** [iVanPan/react-native-qqsdk#20]
这是什么原因呢?

我看了所有React 这个打头的好像都找不到?  不懂这块的开发, 按照步骤一步步配置下来的. 不知道为何会少?

**Comment by iVanPan** [comment]
你 React 这个库有没有连接正确 看一下 react native 官网 怎么配置 @HengCC

**Comment by HengCC** [comment]
React/RCTBridge.h not found 

React/RCTConvert.h not found

**Comment by HengCC** [comment]
连接正确了. 我配置了header search path 而且肯定有.

我google后有个解决方案, 现在这样写是能编译通过了. 

```
#import <RCTBridge.h>
#import <RCTEventEmitter.h>
#import <RCTBridgeModule.h>
```

其他类似的地方都修改了, 删除了`React/`

我的react-native版本是0.39.2

**Comment by iVanPan** [comment]
@HengCC  好吧 从 0.40 开始 iOS 的头文件不一样了，所有这个插件最新的版本是从 0.40 开始支持的
