### ISSUE TITLE
Android端，news类型的消息，若无图片，会报错

### ISSUE THREAD

**Issue by fenglu09** [iVanPan/react-native-qqsdk#22]
RT。
在`Android`端，QQ分享，type为`news`，若`image = null` 或者 `image = ''`就会报错

**Comment by iVanPan** [comment]
@fenglu09  能给一下 错误log 嘛？

**Comment by fenglu09** [comment]
![image](https://user-images.githubusercontent.com/12250129/33834464-fc5a490c-debd-11e7-911b-24043f1d2f14.png)

**Comment by iVanPan** [comment]
@fenglu09  好的 感谢，周末的时候我会修改一下的

**Comment by fenglu09** [comment]
如果能够快点解决就更好了，现在项目赶着上线。

非常感谢无私奉献。

**Comment by iVanPan** [comment]
@fenglu09  不好意思，主要是我没有 Android 机，下班到家都是九点半以后的，周末要借个 Android机才好调试，希望谅解

**Comment by fenglu09** [comment]
嗯，好的，这个问题其实在模拟器上面都可以测试出来，不需要真机

**Comment by fenglu09** [comment]
请问这个问题解决了吗？
