### ISSUE TITLE
ios 上分享后返回app，概率性的使App重启

### ISSUE THREAD

**Issue by jiangbo2015** [iVanPan/react-native-qqsdk#23]
# 系统环境
- Mac 10.12
- RN 0.43
- qqsdk 0.8.0

# 步骤
分享到QQ，返回app以后， 一定概率性的会使app重启

**Comment by iVanPan** [comment]
@jiangbo2015  是Android 端吧？ Android 端的话 你手动改一下 android:launchMode

**Comment by jiangbo2015** [comment]
你好，是ios的，我们的应用是iPad上使用

**Comment by iVanPan** [comment]
@jiangbo2015  最新的 0.8.2 的版本试过吗？也这样？

**Comment by jiangbo2015** [comment]
closed:在webGL的页面这样操作会闪退，不是该SDK的问题，是ios对webGL调用限制
