### ISSUE TITLE
Can it support iOS 8.0?

### ISSUE THREAD

**Issue by linytsysu** [iVanPan/react-native-qqsdk#3]
我发现 iOS deployment target 是 10.1，这样无法支持低版本的 iOS 系统：
<img width="415" alt="2017-03-13 2 27 38" src="https://cloud.githubusercontent.com/assets/8371161/23843832/62e9295a-07f9-11e7-8d17-50d80852858a.png">
<img width="956" alt="2017-03-13 2 34 25" src="https://cloud.githubusercontent.com/assets/8371161/23844004/6f02dbfe-07fa-11e7-9119-e133cee81bec.png">
我想请问这个库能不能支持 iOS 8.0？如果支持的话，我把iOS Deployment Target直接改成 8.0 是否就可以了？

**Comment by iVanPan** [comment]
@linytsysu  可以支持的，多谢提醒，我马上去修改一下发个版本

**Comment by linytsysu** [comment]
我使用的是支持RN < 0.40的0.6.4版本，我直接修改 react-native-qqsdk 的 iOS Deployment target是否就可以了？

**Comment by iVanPan** [comment]
@linytsysu  是的
