### ISSUE TITLE
appid

### ISSUE THREAD

**Issue by lanjinli** [iVanPan/react-native-qqsdk#30]

**Comment by lanjinli** [comment]
我在package.json配置会报错
![tim 20190305152401](https://user-images.githubusercontent.com/42225063/53787738-c1a60400-3f5a-11e9-9430-1bd54bfa1879.png)
![screenshot_1551770649](https://user-images.githubusercontent.com/42225063/53787744-c5398b00-3f5a-11e9-864c-1ac1036f8bd7.png)

**Comment by xinzsky** [comment]
不能为空字符串，需要填上你从QQ开放平台申请的app id
