### ISSUE TITLE
分享失败，提示“应用未上线（错误码9001010）”

### ISSUE THREAD

**Issue by Jason5514** [iVanPan/react-native-qqsdk#33]
安卓设备分享至QQ，分享失败且弹框“应用未上线（错误码9001010）” 

版本信息：
react-native：0.48.4
react：16.0.0-alpha.12

在之前都是使用正常，近期有反馈分享失败案例，求助.

**Comment by iVanPan** [comment]
这个你要去询问一下腾讯
