### ISSUE TITLE
ios 按照步骤集成之后编译报错，看看怎么回事？

### ISSUE THREAD

**Issue by keyuanupup** [iVanPan/react-native-qqsdk#4]
![3](https://cloud.githubusercontent.com/assets/11323825/23995170/60d26adc-0a83-11e7-8286-fba015f9cde4.png)

**Comment by iVanPan** [comment]
@YO-huang  RCTLinkingManager 重复定义了，是单独一个工程用了单独这个插件还是说和其他插件一起用了？

**Comment by keyuanupup** [comment]
@iVanPan 和其他的插件一起用的

**Comment by iVanPan** [comment]
@YO-huang  可能其他插件里面也定义了RCTLinkingManager 用了CodePush？

**Comment by iVanPan** [comment]
@YO-huang  Xcode 里面错误log能展开来看详情吗？ 看看里面有没有说明和那个冲突了

**Comment by keyuanupup** [comment]
![2](https://cloud.githubusercontent.com/assets/11323825/23995851/541674b6-0a86-11e7-9166-fe0aa01302e8.png)   @iVanPan 这是报错的截图。用到的第三方依赖库很多，我不确定哪一个用了CodePush。

**Comment by keyuanupup** [comment]
@iVanPan "dependencies": {
    "fetch-http-client": "^1.0.1",
    "mobx": "^3.1.2",
    "mobx-react": "^4.1.1",
    "react": "15.4.1",
    "react-native": "0.40.0",
    "react-native-baidu-map": "^0.5.0",
    "react-native-check-box": "^1.0.4",
    "react-native-easy-toast": "^1.0.5",
    "react-native-image-picker": "^0.25.6",
    "react-native-map-linking": "^1.0.1",
    "react-native-modal-datetime-picker": "^4.1.0",
    "react-native-photo-view": "^1.2.0",
    "react-native-picker": "^4.0.18",
    "react-native-pullrefresh-scrollview": "^1.1.0",
    "react-native-qqsdk": "^0.7.0",
    "react-native-root-toast": "^1.0.3",
    "react-native-storage": "^0.1.5",
    "react-native-swiper": "^1.5.4",
    "react-native-tab-navigator": "^0.3.3",
    "react-native-wechat": "^1.9.0",
    "react-native-yunpeng-alipay": "^1.1.4",
    "react-redux": "^5.0.2",
    "react-timer-mixin": "^0.13.3",
    "redux": "^3.6.0",
    "redux-persist": "^4.3.1",
    "redux-thunk": "^2.2.0"
  },
这是目前用到的所有第三方依赖库

**Comment by iVanPan** [comment]
@YO-huang  估计是baidumap，能看一下你的AppDelegate.h 和AppDelegate.m 文件吗？

**Comment by iVanPan** [comment]
wechat 也有可能

**Comment by keyuanupup** [comment]
![4](https://cloud.githubusercontent.com/assets/11323825/23996233/a361530a-0a87-11e7-9097-5e19cc97b8d1.png)
@iVanPan  这是我的Appdelegate.m，我试试把baidumap和wechat去掉，再试一试。

**Comment by iVanPan** [comment]
@YO-huang  RN0.40以上用#import <React/RCTLinkingManager.h>

**Comment by keyuanupup** [comment]
@iVanPan 
![image](https://cloud.githubusercontent.com/assets/11323825/23996522/a532aab6-0a88-11e7-9660-5ffd3b957cf4.png)

**Comment by iVanPan** [comment]
@YO-huang  SDK类库没有找到，你是手动添加的还是react-native-link 过来的？新建个demo工程 你试试看，我这边一点问题都没有 用的是rn 0.41的版本

**Comment by keyuanupup** [comment]
@iVanPan 好的，谢谢 我自己再尝试一下，有思路了。多谢。
