### ISSUE TITLE
undefined is not a object(evaluating 'QQSDK.checkClientInstalled')

### ISSUE THREAD

**Issue by wanghche** [iVanPan/react-native-qqsdk#9]
I build success and will run on simulator,but ios show the error as title.android is ok.
I do every step of ios link.

react:16.0.0-alpha.3,
react-native:0.43.0-rc.3

Is there anyone face same issue?￼
![wx20170518-183755](https://cloud.githubusercontent.com/assets/12526399/26199418/790ef048-3bfc-11e7-9013-f2879f625888.png)

**Comment by iVanPan** [comment]
![2017-05-18 19 40 19](https://cloud.githubusercontent.com/assets/1687276/26200678/e670c382-3c01-11e7-8ba1-187fe49b3e40.png)
![2017-05-18 19 35 30](https://cloud.githubusercontent.com/assets/1687276/26200691/f835787e-3c01-11e7-8d0a-42070a915448.png)
![simulator screen shot 2017 5 18 19 35 16](https://cloud.githubusercontent.com/assets/1687276/26200695/fc9d4450-3c01-11e7-841f-7b6335cb4039.png)
I just do some test,everything is ok.

**Comment by wanghche** [comment]
@iVanPan Thx.I run successfully the same code on IOS simulator of my another Mac.It seems this is my development environment issue.
